version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    assignees:
      - blck-snwmn
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    groups:
      dependencies:
        patterns:
          - "*"
