name: Actions Security

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  actions-security:
    name: Actions Security
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install tools
        uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.62.3
      - name: Check pinned Actions
        run: pinact run --check
      - name: Audit GitHub Actions
        run: zizmor --format github .
